def meniu_principal():

    print("--- Meniu principal ---")
    print(" 0. Exit.")
    print(" 1. Adaugă persoană.")
    print(" 2. Adaugă eveniment.")
    print(" 3. Modifică persoană")
    print(" 4. Modifică eveniment.")
    print(" 5. Ștergere persoană.")
    print(" 6. Ștergere eveniment.")
    print(" 7. Căutare persoană.")
    print(" 8. Căutare eveniment.")
    print(" 9. Generare persoană/e.")
    print(" 10. Afișare persoane.")
    print(" 11. Afișare evenimente.")
    print(" 12. Înscrie persoană la eveniment.")
    print(" 13. Lista de evenimente la care participă o persoană ordonat alfabetic după descriere, după dată")
    print(" 14. Persoane participante la cele mai multe evenimente")
    print(" 15. Primele 20% evenimente cu cei mai mulți participanți")
    print(" 17. Sortează persoane cu Selection Sort")
    print(" 18. Sortează evenimente cu Shake Sort")